[package]
name = "lane_lunacy"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
vulkano = "0.35"
ash = "=0.38.0"
winit = "0.30"
glam = "0.29"
fontdue = "0.9"
gltf = "1.4"
image = "0.25"
half = "2.7"
smallvec = "1.8"
rodio = { version = "0.22", default-features = false, features = ["playback"] }

[build-dependencies]
shaderc = { version = "0.10.1", features = ["build-from-source"] }
